import os
from pathlib import Path

class Parameters:
    """
    Configurable parameters for RecruitNepal's AI Interview Bot.
    """

    MODEL = "gpt-4o-mini"
    REPORTS_DIR = Path("interview_reports")
    REPORTS_DIR.mkdir(exist_ok=True)
    
    MAX_QUESTIONS = 7
    QUESTIONS_PER_SECTION = 3

    INITIAL_GREETING = """
    Hello! I'm the AI interviewer for RecruitNepal. Before we begin the interview, 
    could you please tell me your name?
    """

    SECTIONS = {
        "technical": "Technical Skills and Experience",
        "behavioral": "Work Style and Cultural Fit",
        "situational": "Problem Solving and Decision Making"
    }

    QUESTIONS_PROMPT = """
    Create exactly 3 interview questions for the {section} section. Questions should be:
    - Clear and concise (max 20 words each)
    - Specific to the section theme
    - Designed to assess candidate qualifications
    
    Format as a simple numbered list (1., 2., 3.)
    Return ONLY the questions, no additional text.
    """

    EVALUATION_PROMPT = """
    Evaluate the candidate based on their responses:

    Candidate Name: {name}
    Interview Responses:
    {interview_text}

    Provide a concise evaluation covering:
    1. Technical Competency
    2. Cultural Fit
    3. Problem-Solving Ability
    4. Overall Recommendation (Proceed/Need More Information/Not Suitable)

    Keep the evaluation constructive and actionable.
    """

    REPORT_TEMPLATE = """# Candidate Interview Report
Generated: {timestamp}

## Candidate Information
- Name: {name}
- Interview Date: {date}

## Interview Questions and Responses
{interview_text}

## AI Evaluation
{evaluation}

## Final Recommendation
{recommendation}

---
Generated by RecruitNepal AI Interview Bot
"""